runtime: python39

entrypoint: gunicorn -b :$PORT myproject.wsgi

handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
  
env_variables:
  DATABASE_URL: "mysql://db_user:secure_password@/foodbank_db?unix_socket=/cloudsql/db-group8-438602:us-central1:foodbankgroup8"

