runtime: python311

# entrypoint: gunicorn -b :$PORT myproject.wsgi
runtime_config:
  python_version: 3.11
handlers:
  - url: /static
    static_dir: static/

  - url: /.*
    script: auto
  
# env_variables:
#   DATABASE_URL: "mysql://db_user:secure_password@/foodbank_db?unix_socket=/cloudsql/db-group8-438602:us-central1:foodbankgroup8"



# [START django_app]
# runtime: python39

# handlers:
# # This configures Google App Engine to serve the files in the app's static
# # directory.
# - url: /static
#   static_dir: static/

# # This handler routes all requests not caught above to your main app. It is
# # required when static routes are defined, but can be omitted (along with
# # the entire handlers section) when there are no static files defined.
# - url: /.*
#   script: auto
# # [END django_app]